### ISSUE TITLE
Incorrect toolbar height

### ISSUE THREAD

**Issue by austinjackson** [jonathannaguin/BarcodeScanner#2]
On iOS 7, the toolbar at the bottom of the screen containing the cancel button is too short when displayed on an iPad in landscape orientation.  The cancel text extends above the toolbar.

**Comment by jonathannaguin** [comment]
The height of the toolbar is adjusting automatically when the device rotates. So that is the default behaviour, if you want to change it, you can edit the OverlayView.m

**Comment by austinjackson** [comment]
Correct, but the height of the cancel button/text does not adjust with it, extending above the toolbar.

**Comment by austinjackson** [comment]
Oh, and thank you for looking into this!

**Comment by jonathannaguin** [comment]
I tested on a iPad 2 and label is not above the toolbar, but inside. It seems it is not center, though.

**Comment by austinjackson** [comment]
The problem occurs (for me) on a retina iPad mini.
