### ISSUE TITLE
Build errors with iOS SDK 7.1, Xcode 5.1 5B130a

### ISSUE THREAD

**Issue by austinjackson** [jonathannaguin/BarcodeScanner#3]
An app with the plugin installed won't build on the latest Xcode when deploying to a 64 bit device.  There is some information at the link below that provides a fix for the main cordova project.

http://shazronatadobe.wordpress.com/2014/03/12/xcode-5-1-and-cordova-ios/

**Comment by jonathannaguin** [comment]
I changed the architecture of the plugin to have "Standard architectures (armv7, armv7s, arm64)". I haven't tested but I think it should work with the latest version of Cordova.

**Comment by austinjackson** [comment]
Getting an error when running "cordova build" with the patch:

ld: warning: ignoring file /com.phonegap.plugins.barcodescanner/libZXingWidgetLibrary.a, missing required architecture i386 in file /com.phonegap.plugins.barcodescanner/libZXingWidgetLibrary.a (2 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ZXingWidgetController", referenced from:
      objc-class-ref in CDVBarcodeScanner.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jonathannaguin** [comment]
Are you trying to build against the iOS Simulator? The library won't work in the simulator because there isn't a way to use the camera of the Mac.

**Comment by austinjackson** [comment]
Nope.  Just running "cordova build" to get an Xcode project, then deploying to Retina iPad mini and iPhone 5 from Xcode.

**Comment by jonathannaguin** [comment]
I uploaded again the library. Try again :)

**Comment by austinjackson** [comment]
No go.  "cordova build" throws a bunch of errors.  If I ignore them and open the project in Xcode and attempt to build, I get 39 Apple Mach-O Linker Errors.

**Comment by jonathannaguin** [comment]
Can you provide the output? I have tried on my machine and it was working fine, but I don't have a 64 bits device... Yet

**Comment by jeeff** [comment]
I have a same problem and hopefully found a solution. Everythink worked when i have a project with deploying target set fo 6.0. But when i change it to 7.0 or 8.0 there was a lot of i386 linker errors. I was searching for solutions for two days. I found a solution here:

http://stackoverflow.com/questions/19271856/undefined-symbols-for-architecture-error-when-deployment-target-is-7-0

the solution is to include the 'stdc++.6.0.9.dylib' in xcode at tab Build Settings -> Link binnary with libraries.

Thanks for your barcode scanner ;-)
