### ISSUE TITLE
Required libs and frameworks for ios

### ISSUE THREAD

**Issue by alekseypotapov-dev** [jonathannaguin/BarcodeScanner#4]
There're libs, required to make this stuff work:

```
AudioToolbox Framework
AVFoundation Framework 
```

and 

```
libiconv.dylib
```

Just in case one faces this problem

(may be should be added to readme)

**Comment by jonathannaguin** [comment]
Hi there,

Yes, those libs are needed, but they have been already added in the `plugin.xml` following the Cordova format. No need to mention it in the README.

**Comment by alekseypotapov-dev** [comment]
You're right. But those, who use (like me) terminal:

```
cordova plugin add <repo_name>
```

You should include these libs

P.S. In readme the link https://github.com/apache/cordova-plugman/blob/master/plugin_spec.md is broken

**Comment by jonathannaguin** [comment]
I am using the terminal as well and the command add automatically the frameworks on my project...
